// apps/angular/src/app/ui/sorting-progress-chart/sorting-progress-chart.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

import { SortStep } from '../../sorting/sorting.models';

@Component({
  selector: 'app-sorting-progress-chart',
  standalone: true,
  templateUrl: './sorting-progress-chart.component.html',
  styleUrl: './sorting-progress-chart.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SortingProgressChartComponent {
  readonly title = input('Sorting Progress');
  readonly progress = input.required<SortStep>();
  readonly barColor = input('#1f2937');
  readonly compareColor = input('#f59e0b');
  readonly swapColor = input('#ef4444');
  readonly pivotColor = input('#3b82f6');
  readonly sortedColor = input('#10b981');
  readonly height = input(300);

  readonly bars = computed(() => {
    const progress = this.progress();
    const values = progress.values ?? [];
    const maxValue = Math.max(...values, 1);
    const comparing = new Set(progress.comparing ?? []);
    const swapping = new Set(progress.swapping ?? []);
    const sorted = new Set(progress.sorted ?? []);

    return values.map((value, index) => {
      let fill = this.barColor();

      if (sorted.has(index)) {
        fill = this.sortedColor();
      } else if (swapping.has(index)) {
        fill = this.swapColor();
      } else if (progress.pivot === index) {
        fill = this.pivotColor();
      } else if (comparing.has(index)) {
        fill = this.compareColor();
      }

      return {
        index,
        value,
        fill,
        height: `${Math.max((value / maxValue) * 100, 4)}%`,
      };
    });
  });

  readonly barCount = computed(() => this.progress().values?.length ?? 0);
  readonly isDense = computed(() => this.barCount() >= 128);
  readonly isUltraDense = computed(() => this.barCount() >= 192);
  readonly gridTemplateColumns = computed(
    () => `repeat(${Math.max(this.barCount(), 1)}, minmax(0, 1fr))`,
  );

  readonly legend = computed(() => [
    { label: 'Normal', color: this.barColor() },
    { label: 'Compare', color: this.compareColor() },
    { label: 'Swap', color: this.swapColor() },
    { label: 'Pivot', color: this.pivotColor() },
    { label: 'Sorted', color: this.sortedColor() },
  ]);

  readonly gridLines = [20, 40, 60, 80];
}

<div class="chart-shell">
  @if (title()) {
    <h3 class="chart-title">{{ title() }}</h3>
  }

  <div class="chart-stage" [class.chart-stage--dense]="isDense()" [style.height.px]="height()">
    @for (line of gridLines; track line) {
      <span class="grid-line" [style.bottom.%]="line"></span>
    }

    <div class="bars" [class.bars--dense]="isDense()" [style.grid-template-columns]="gridTemplateColumns()">
      @for (bar of bars(); track bar.index) {
        <div
          class="bar"
          [class.bar--dense]="isDense()"
          [class.bar--ultra-dense]="isUltraDense()"
          [style.height]="bar.height"
          [style.background]="bar.fill"
          [attr.aria-label]="'Element ' + bar.index + ', value ' + bar.value"
          [title]="'Index ' + bar.index + ': ' + bar.value"
        ></div>
      }
    </div>
  </div>

  <div class="legend">
    @for (entry of legend(); track entry.label) {
      <span class="legend-item">
        <span class="legend-dot" [style.background]="entry.color"></span>
        {{ entry.label }}
      </span>
    }
  </div>
</div>

// apps/react/src/components/dashboard/SortingProgressChart.tsx
import { memo, useMemo } from "react";

export type SortingProgress = {
  values: number[];
  comparing?: number[];
  swapping?: number[];
  pivot?: number | null;
  sorted?: number[];
};

export type SortingProgressChartProps = {
  title?: string;
  progress: SortingProgress;
  barColor?: string;
  compareColor?: string;
  swapColor?: string;
  pivotColor?: string;
  sortedColor?: string;
  height?: number;
};

const LegendDot = ({ color, label }: { color: string; label: string }) => {
  return (
    <span className="inline-flex items-center gap-2">
      <span
        className="h-2.5 w-2.5 rounded-sm"
        style={{ backgroundColor: color }}
      />
      {label}
    </span>
  );
};

export const SortingProgressChart = memo(function SortingProgressChart({
  title = "Sorting Progress",
  progress,
  barColor = "#1f2937",
  compareColor = "#f59e0b", // amber-500
  swapColor = "#ef4444", // red-500
  pivotColor = "#3b82f6", // blue-500
  sortedColor = "#10b981", // emerald-500
  height = 300,
}: SortingProgressChartProps) {
  const {
    values,
    comparing = [],
    swapping = [],
    pivot = null,
    sorted = [],
  } = progress;
  const comparingSet = useMemo(() => new Set(comparing), [comparing]);
  const swappingSet = useMemo(() => new Set(swapping), [swapping]);
  const sortedSet = useMemo(() => new Set(sorted), [sorted]);

  const bars = useMemo(() => {
    const maxValue = Math.max(...values, 1);

    return values.map((value, index) => {
      let fill = barColor;

      if (sortedSet.has(index)) fill = sortedColor;
      else if (swappingSet.has(index)) fill = swapColor;
      else if (pivot === index) fill = pivotColor;
      else if (comparingSet.has(index)) fill = compareColor;

      return {
        index,
        value,
        fill,
        height: `${Math.max((value / maxValue) * 100, 4)}%`,
      };
    });
  }, [
    barColor,
    compareColor,
    comparingSet,
    pivot,
    sortedColor,
    sortedSet,
    swapColor,
    swappingSet,
    values,
  ]);
  const barCount = values.length;
  const isDense = barCount >= 128;
  const isUltraDense = barCount >= 192;
  const gridLines = [20, 40, 60, 80];

  return (
    <div className="sort-chart-shell rounded-2xl border bg-card/90 p-4">
      {title ? (
        <h3 className="mb-3 font-medium text-card-foreground text-sm">
          {title}
        </h3>
      ) : null}
      <div
        className={`sort-chart-stage${isDense ? " sort-chart-stage--dense" : ""}`}
        style={{ height }}
      >
        {gridLines.map((line) => (
          <span
            key={line}
            className="sort-chart-grid-line"
            style={{ bottom: `${line}%` }}
          />
        ))}
        <div
          className={`sort-chart-bars${isDense ? " sort-chart-bars--dense" : ""}`}
          style={{
            gridTemplateColumns: `repeat(${Math.max(barCount, 1)}, minmax(0, 1fr))`,
          }}
        >
          {bars.map((bar) => (
            <div
              key={bar.index}
              className={`sort-chart-bar${isDense ? " sort-chart-bar--dense" : ""}${isUltraDense ? " sort-chart-bar--ultra-dense" : ""}`}
              style={{ height: bar.height, background: bar.fill }}
              aria-label={`Element ${bar.index}, value ${bar.value}`}
              title={`Index ${bar.index}: ${bar.value}`}
            />
          ))}
        </div>
      </div>
      <div className="mt-3 flex flex-wrap items-center gap-3 text-muted-foreground text-xs">
        <LegendDot color={barColor} label="Normal" />
        <LegendDot color={compareColor} label="Compare" />
        <LegendDot color={swapColor} label="Swap" />
        <LegendDot color={pivotColor} label="Pivot" />
        <LegendDot color={sortedColor} label="Sorted" />
      </div>
    </div>
  );
});
